### ISSUE TITLE
Dessin de pendu man!!!

### ISSUE THREAD

**Issue by SuperBest27** [ThomasBest22/Hangman#1]
Hé wesh là pk y a pas de dessin de pendu ?
Chuis désolé mais ton jeu il est pt!!!
Vazy fix ça ou je me désabonne.
Azy salut man

**Comment by Thomsd2** [comment]
Réparé dans la [v2.1](https://github.com/ThomasBest22/Hangman/releases/tag/v2.1)

**Comment by SuperBest27** [comment]
Merci Man
